#!/bin/sh
read -p "Enter the query: " -r query
python2 201501244.py "$query"

#query="select max(A) from table1;select A,D from table1,table2;select A,B from table1 where A=775 OR B=803;select A,D from table1,table2 where table1.B=table2.B;select * from table1,table2 where table1.B=table2.B;select A from table4;"
